# Generated by Django 5.1.6 on 2025-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_admission_year_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
